name: Builds

on:
  push:
    branches:
        - main
        - indev
  pull_request:
    types: [assigned]
    branches:
        - main
        - indev
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.changed }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Check changes :D
        id: changes
        run: |
          if [[ `git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E -v ".\.md|\.github/|\.vscode/|\.gitignore|.\.ase|.\.aseprite" | grep "src/"` ]] || [[ "${{ github.event_name }}" = "workflow_dispatch" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "[DEBUG] - it should build :D"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "[DEBUG] - dont build >:("
          fi

          if [[ "${{ github.ref_name }}" != "main" ]]; then
            echo "suffix='-${{ github.ref_name }}'" >> $GITHUB_ENV
          fi
  build:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.changed == 'true'

    steps:
      - uses: actions/checkout@v5

      - name: Set current date as env variable # pacola if coyping from https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows was a challenge:
        run: echo "NOW=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: do the thing pls
        run: |
          cd src/
          zip -r ../luigi${{ env.suffix }}-${{ env.NOW }}.pk3 .

      - name: send thing to the action tab
        uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: luigi${{ env.suffix }}
          path: luigi${{ env.suffix }}-${{ env.NOW }}.pk3

      - name: could you preetty please send the file to the discord
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: luigi${{ env.suffix }}-${{ env.NOW }}.pk3